// Generated by ts-to-zod
import { z } from "zod";

export const fillLinearSchema = z.object({
  type: z.literal("fill_linear"),
  x0: z.number(),
  y0: z.number(),
  x1: z.number(),
  y1: z.number(),
  colorstops: z.array(z.tuple([z.number(), z.string()])),
});

export const fillRadialSchema = z.object({
  type: z.literal("fill_radial"),
  x0: z.number(),
  y0: z.number(),
  x1: z.number(),
  y1: z.number(),
  r0: z.number(),
  r1: z.number(),
  colorstops: z.array(z.tuple([z.number(), z.string()])),
});

export const fillConicSchema = z.object({
  type: z.literal("fill_conic"),
  x: z.number(),
  y: z.number(),
  theta: z.number(),
  colorstops: z.array(z.tuple([z.number(), z.string()])),
});

export const bezierSchema = z.tuple([
  z.number(),
  z.number(),
  z.number(),
  z.number(),
  z.number(),
  z.number(),
]);

export const drawImageCommandSchema = z.object({
  type: z.literal("drawImage"),
  img: z.string(),
  x: z.number(),
  y: z.number(),
});

export const drawLineCommandSchema = z.object({
  type: z.literal("drawLine"),
  x0: z.number(),
  y0: z.number(),
  x1: z.number(),
  y1: z.number(),
  color: z.string().optional(),
  width: z.number().optional(),
});

export const drawTextCommandSchema = z.object({
  type: z.literal("drawText"),
  text_: z.string(),
  x: z.number(),
  y: z.number(),
  width: z.union([z.number(), z.undefined()]).optional(),
  color: z.string().optional(),
  size: z.number().optional(),
  font: z.string().optional(),
});

const pointSchema = z.tuple([z.number(), z.number()]);

const rectSchema = z.tuple([z.number(), z.number(), z.number(), z.number()]);

const namedPointSchema = z.tuple([z.string(), z.number(), z.number()]);

const pointFillLinearSchema = z.object({
  type: z.literal("fill_linear"),
  p0: z.string(),
  p1: z.string(),
  colorstops: z.array(z.tuple([z.number(), z.string()])),
});

const pointFillRadialSchema = z.object({
  type: z.literal("fill_radial"),
  p0: z.string(),
  p1: z.string(),
  r0: z.number(),
  r1: z.number(),
  colorstops: z.array(z.tuple([z.number(), z.string()])),
});

const pointFillConicSchema = z.object({
  type: z.literal("fill_conic"),
  p0: z.string(),
  theta: z.number(),
  colorstops: z.array(z.tuple([z.number(), z.string()])),
});

const pointFillSchema = z.union([
  z.string(),
  pointFillLinearSchema,
  pointFillRadialSchema,
  pointFillConicSchema,
]);

const outlineSchema = z.object({
  thickness: z.number(),
  color: z.string(),
});

const shapeTypesSchema = z.union([
  z.literal("line"),
  z.literal("bezier"),
  z.literal("smooth bezier"),
  z.literal("polygon"),
  z.literal("circle"),
  z.literal("ellipse"),
  z.literal("bezier shape"),
  z.literal("smooth bezier shape"),
]);

const shapeSchema = z.object({
  parent_layer: z.string(),
  points: z.array(z.tuple([z.string(), z.number(), z.number()])),
  name: z.string(),
  type: shapeTypesSchema,
  fill: z.union([z.string(), pointFillSchema]).optional(),
  outline: outlineSchema.optional(),
  visible: z.boolean(),
  outline_visible: z.boolean(),
  insertion_point: z.string().optional(),
  tag: z.array(z.string()),
});

const layerSchema = z.object({
  name: z.string(),
  shapes: z.array(shapeSchema),
});

const fillstyleSchema = z.any();

const drawCircleCommandSchema = z.any();

const drawPolygonCommandSchema = z.any();

const drawBezierCurveCommandSchema = z.any();

const drawBezierShapeCommandSchema = z.any();

const drawCommandSchema = z.any();

const point3dSchema = z.any();

export const drawRectangleCommandSchema = z.object({
  type: z.literal("drawRectangle"),
  tlx: z.number(),
  tly: z.number(),
  brx: z.number(),
  bry: z.number(),
  color: fillstyleSchema.optional(),
  width: z.number().optional(),
  fill: z.boolean().optional(),
  transparency: z.number().optional(),
});

export const drawRectangle2CommandSchema = z.object({
  type: z.literal("drawRectangle2"),
  tlx: z.number(),
  tly: z.number(),
  width: z.number(),
  height: z.number(),
  color: fillstyleSchema.optional(),
  widthA: z.number().optional(),
  fill: z.boolean().optional(),
  transparency: z.number().optional(),
});

export const drawEllipseCommandSchema = z.object({
  type: z.literal("drawEllipse"),
  posx: z.number(),
  posy: z.number(),
  brx: z.number(),
  bry: z.number(),
  color: fillstyleSchema.optional(),
  transparency: z.number().optional(),
  rotate: z.number().optional(),
  start: z.number().optional(),
  end: z.number().optional(),
  fill: z.boolean().optional(),
  stroke_width: z.number().optional(),
});

export const drawEllipseCRCommandSchema = z.object({
  type: z.literal("drawEllipseCR"),
  cx: z.number(),
  cy: z.number(),
  rx: z.number(),
  ry: z.number(),
  color: fillstyleSchema.optional(),
  transparency: z.number().optional(),
  rotate: z.number().optional(),
  start: z.number().optional(),
  end: z.number().optional(),
  fill: z.boolean().optional(),
  stroke_width: z.number().optional(),
});

export const drawRoundedRectangleCommandSchema = z.object({
  type: z.literal("drawRoundedRectangle"),
  x0: z.number(),
  y0: z.number(),
  x1: z.number(),
  y1: z.number(),
  r1: z.number(),
  r2: z.number(),
  color: fillstyleSchema.optional(),
  width: z.number().optional(),
  fill: z.boolean().optional(),
});

const displayTotalSchema = z.object({
  points: z.array(namedPointSchema),
  layers: z.array(layerSchema),
  zoom: point3dSchema,
  layer_visibility: z.record(z.boolean()),
  show_points: z.union([
    z.literal("none"),
    z.literal("shape"),
    z.literal("layer"),
    z.literal("all"),
  ]),
  show_labels: z.boolean(),
  selected_point: z.string().optional(),
  selected_shape: z.string().optional(),
  selected_layer: z.string(),
  true_points: z.boolean(),
  total_points: z.number(),
  total_shapes: z.number(),
  message: z.string(),
});

const matrix3Schema = z.tuple([point3dSchema, point3dSchema, point3dSchema]);
